---
- hosts: localhost
  tasks:
  - check_http_osx:
      checks: &checks
      - name: slash
        url: https://google.com/
        no_follow_redirect: true
        expected:
          status_code: 301
          # status_code: 303
      - name: /foo
        url: https://google.com/foo
        no_follow_redirect: true
        expected:
          status_code: 404

# - hosts: bastion
#   connection: ssh
#   tasks:
#   - check_http:
#       checks: *checks
