---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - check_http_osx:
      checks: &checks
      - name: /
        url: https://google.com/
        no_follow_redirect: true
        expected:
          status_code: 301
      - name: /foo
        url: https://google.com/foo
        no_follow_redirect: true
        expected:
          status_code: 404

- hosts: bastion
  gather_facts: false
  connection: ssh
  tasks:
  - check_http:
      checks: *checks
