---
- hosts: localhost
  name: runs go binary on macos host
  tasks:
    - check_http_osx:
        checks: &checks
          - name: google.ca/
            url: https://google.ca
            no_follow_redirect: true
            expected:
              status_code: 301

- hosts: remote_linux_host
  name: runs go binary on linux host
  tasks:
    - check_http_linux:
        checks: *checks
